### PR TITLE
refactor to support filtering

### PR DESCRIPTION
**Pull request by daler**
After a lot of experimenting, I've settled on what I think is a good approach for filtering. This pull request incorporates all of that. The pipeline now finishes with one file containing all features aggregated and uniquely named and ready to use for training models, and another file containing drug response data, processed and ready for training.

The new [`run_info`](http://daler.github.io/Pharmacogenomics_Prediction_Pipeline_P3/configuration.html#run-info) section of the config file allows per-run specification of which samples and drugs get into the model. It also allows you to specify arbitrary filtering functions for filtering features and more fine-grained control about which values are used as the response variable.

The [filtering](http://daler.github.io/Pharmacogenomics_Prediction_Pipeline_P3/filtering.html#filtering) page in the docs has more discussion on how things work and why they're set up that way.

I also did some cleanup. For example, instead of `runall.snakefile`, there's now just `Snakefile` which is the default filename that snakemake looks for. You can do a run of the pipeline from start to finish using the example data using these two commands:

```
snakemake prepare_example_data
snakemake
```

The first unzips the example data, and the second runs the entire pipeline. You can use the `-j` option for using multiple processors. You can make a PNG of the DAG with:

```
snakemake --rulegraph | dot -Tpng -Grankdir=LR > dag.png
```

which looks like this:

a

Please take a look through the docs and code in this PR and let me know if anything is unclear, not explained well, or doesn't make sense.

### CODE REVIEW

**Comment by seandavi** [comment]
One word--wow!!!

**Comment by PedalheadPHX** [comment]
## Very impressive Ryan.  Do you think its ready for some independent test runs?

Jonathan Keats   |   Assistant Professor   |   Integrated Cancer Genomics Division
Translational Genomics Research Institute (TGen)
jkeats@tgen.orgmailto:jkeats@tgen.org   |   www.keatslab.orghttp://www.keatslab.org/
445 N. Fifth Street   |   Phoenix, AZ 85004
(W) 602-343-8690   |   (M) 480-543-0634

---

---

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

On Oct 2, 2015, at 10:21 AM, Ryan Dale <notifications@github.com<mailto:notifications@github.com>> wrote:

After a lot of experimenting, I've settled on what I think is a good approach for filtering. This pull request incorporates all of that. The pipeline now finishes with one file containing all features aggregated and uniquely named and ready to use for training models, and another file containing drug response data, processed and ready for training.

The new run_infohttp://daler.github.io/Pharmacogenomics_Prediction_Pipeline_P3/configuration.html#run-info section of the config file allows per-run specification of which samples and drugs get into the model. It also allows you to specify arbitrary filtering functions for filtering features and more fine-grained control about which values are used as the response variable.

The filteringhttp://daler.github.io/Pharmacogenomics_Prediction_Pipeline_P3/filtering.html#filtering page in the docs has more discussion on how things work and why they're set up that way.

I also did some cleanup. For example, instead of runall.snakefile, there's now just Snakefile which is the default filename that snakemake looks for. You can do a run of the pipeline from start to finish using the example data using these two commands:

snakemake prepare_example_data
snakemake

The first unzips the example data, and the second runs the entire pipeline. You can use the -j option for using multiple processors. You can make a PNG of the DAG with:

snakemake --rulegraph | dot -Tpng -Grankdir=LR > dag.png

which looks like this:

[a]https://cloud.githubusercontent.com/assets/115406/10252759/9a8e6cfe-6907-11e5-8f48-6b7aa7c88554.png

Please take a look through the docs and code in this PR and let me know if anything is unclear, not explained well, or doesn't make sense.

---

You can view, comment on, or merge this pull request online at:

  https://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15

Commit Summary
-   add response.snakefile
-   add docs-building script
-   add docs for new build-docs.sh method
-   clean up files from hackathon; runall.snakefile is now Snakefile
-   add drug_response_process script from @ammhub; integrate into main snakefile
-   more comments and docs in Snakefile
-   s/filtered/cleaned/g to be more clear about what's happening
-   dos2unix on drug_response_process.R
-   rm response.snakefile
-   dictionary `output` sections now required
-   output files in snakefiles reflect new dictionary requirement in config.yaml
-   generic filtering functions
-   add name resolver function so we can specify filter funcs in config
-   helper to get target filtered output based on run and config.yaml
-   add filtering to main Snakefile
-   add filterfuncs module
-   make feature snakefiles use the now-required output dict format
-   s/filter_function/feature_filter/g
-   use .dropna() in filter function
-   for actual data use var > 0
-   pipeline_helpers.stitch now uses data_col
-   add helper function to aggregate all features together
-   update config.yaml for new filtering mechanism
-   samples list is now configured per-run
-   drug response values now inferred from per-run config values
-   targets, rule, and input function for aggregating features
-   rule and input function for aggregating responses
-   put run output in prefix dir
-   lots of comments and docs describing the new filtering mechanisms
-   add SIDs.txt for example data
-   edit demo output files in docs to point to new "cleaned" path

File Changes
-   A SIDs.txthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-0 (5)
-   M Snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-1 (372)
-   A build-docs.shhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-2 (47)
-   M config.yamlhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-3 (43)
-   M doc/custom_dot.pyhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-4 (8)
-   M doc/source/configuration.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-5 (65)
-   M doc/source/features.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-6 (30)
-   A doc/source/filtering.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-7 (119)
-   M doc/source/images/all.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-8 (145)
-   M doc/source/images/all_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-9 (0)
-   M doc/source/images/all_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-10 (0)
-   M doc/source/images/cnv.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-11 (30)
-   M doc/source/images/cnv_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-12 (0)
-   M doc/source/images/cnv_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-13 (0)
-   M doc/source/images/cpdb.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-14 (34)
-   M doc/source/images/cpdb_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-15 (0)
-   M doc/source/images/cpdb_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-16 (0)
-   M doc/source/images/exome_variants.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-17 (6)
-   M doc/source/images/exome_variants_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-18 (0)
-   M doc/source/images/exome_variants_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-19 (0)
-   M doc/source/images/go.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-20 (30)
-   M doc/source/images/go_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-21 (0)
-   M doc/source/images/go_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-22 (0)
-   M doc/source/images/msigdb.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-23 (36)
-   M doc/source/images/msigdb_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-24 (0)
-   M doc/source/images/msigdb_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-25 (0)
-   M doc/source/images/normed_counts.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-26 (6)
-   M doc/source/images/normed_counts_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-27 (0)
-   M doc/source/images/normed_counts_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-28 (0)
-   M doc/source/images/zscores.dothttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-29 (10)
-   M doc/source/images/zscores_dag.pdfhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-30 (0)
-   M doc/source/images/zscores_dag.pnghttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-31 (0)
-   M doc/source/index.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-32 (1)
-   M doc/source/metadoc.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-33 (25)
-   M doc/source/topic-snakefiles.rsthttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-34 (12)
-   M features/cnv.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-35 (26)
-   M features/cpdb.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-36 (4)
-   M features/gene_ontology.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-37 (2)
-   M features/msigdb.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-38 (4)
-   M features/normed_counts.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-39 (2)
-   M features/variants.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-40 (6)
-   M features/zscores.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-41 (2)
-   A filterfuncs.pyhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-42 (20)
-   D runall.snakefilehttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-43 (64)
-   D settings.yamlhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-44 (40)
-   A tools/drug_response_process.Rhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-45 (100)
-   M tools/pipeline_helpers.pyhttps://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15/files#diff-46 (101)

Patch Links:
-   https://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15.patch
-   https://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15.diff

**Comment by daler** [comment]
Almost -- let me hook it up to the model training R code, and then it'll be ready for a test run. That'll be pretty straightforward and I'm aiming to have that done early next week.

**Comment by paiyetan** [comment]
Way too cool, Ryan!

On Fri, Oct 2, 2015 at 4:39 PM, Ryan Dale notifications@github.com wrote:

> Almost -- let me hook it up to the model training R code, and then it'll
> be ready for a test run. That'll be pretty straightforward and I'm aiming
> to have that done early next week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3/pull/15#issuecomment-145149511
> .

##

**Comment by khughitt** [comment]
Looks great, Ryan!  The data flow diagram is really useful, too.

**Pull request merged**
